# ==========================================
#                   RR
# ==========================================
# --- RR -> Routers ---
interface eth0
 ip address 10.10.1.2/30
 ip ospf area 0

interface eth1
 ip address 10.10.2.2/30
 ip ospf area 0

interface eth2
 ip address 10.10.3.2/30
 ip ospf area 0

# --- Loopback RR ---
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0

# --- BGP ---
 router bgp 1

# Create group for iBGP routers
# All routers belong to the same AS
# BGP sessions use Loopbacks
# We accept the Loopbacks of our routers as neighbors
 neighbor ibgp peer-group
 neighbor ibgp remote-as 1
 neighbor ibgp update-source lo
 bgp listen range 1.1.1.0/29 peer-group ibgp

# --- BGP EVPN ---
address-family l2vpn evpn
# We activate EVPN for the iBGP group 
# We convert routers into Route Reflector clients
 neighbor ibgp activate
 neighbor ibgp route-reflector-client
exit-address-family


# --- OSPF ---
router ospf
