# ==========================================
#                   RR
# ==========================================

frr defaults traditional
hostname RR


# --- OSPF ---
router ospf
    network 10.10.1.0/30 area 0
    network 10.10.2.0/30 area 0
    network 10.10.3.0/30 area 0
    network 1.1.1.1/32 area 0


# --- BGP ---
 # Create iBGP peer-group
 # All routers use AS 1
 # BGP sessions use Loopbacks
 # Accept Loopback addresses in this range
router bgp 1
    neighbor ibgp peer-group
    neighbor ibgp remote-as 1
    neighbor ibgp update-source lo

    bgp listen range 1.1.1.0/29 peer-group ibgp


 # --- EVPN ---
  # Activate EVPN
  # R1/R2/R3 are Route Reflector clients

 address-family l2vpn evpn
    neighbor ibgp activate
    neighbor ibgp route-reflector-client
 exit-address-family