# ==========================================
#               R2 - FRR
# ==========================================
frr defaults traditional
hostname R2

# ==========================================
# --- OSPF ---
# ==========================================
router ospf
 network 10.10.2.0/30 area 0
 network 1.1.1.3/32 area 0

# ==========================================
# --- BGP ---
# ==========================================
 # RR
 # Use Loopback for BGP
router bgp 1
    neighbor 1.1.1.1 remote-as 1
    neighbor 1.1.1.1 update-source lo

 # ==========================================
 # --- EVPN ---
 # ==========================================
  # Activate EVPN toward RR
  # Advertise local VXLAN VNIs
 address-family l2vpn evpn
    neighbor 1.1.1.1 activate
    advertise-all-vni
 exit-address-family