# ==========================================
#               R3 - FRR
# ==========================================
frr defaults traditional
hostname R3

# ==========================================
# --- OSPF ---
# ==========================================
router ospf
 network 10.10.3.0/30 area 0
 network 1.1.1.4/32 area 0

# ==========================================
# --- BGP ---
# ==========================================
 # RR
 # Use Loopback for BGP
router bgp 1
    neighbor 1.1.1.1 remote-as 1
    neighbor 1.1.1.1 update-source lo

 # ==========================================
 # --- EVPN ---
 # ==========================================
  # Activate EVPN toward RR
  # Advertise local VXLAN VNIs
 address-family l2vpn evpn
    neighbor 1.1.1.1 activate
    advertise-all-vni
 exit-address-family