# ==========================================
#                   RR
# ==========================================
# --- RR -> R1 ---
auto eth0
iface eth0 inet static
    address 10.10.1.2
    netmask 255.255.255.252
# --- RR -> R2 ---
auto eth1
iface eth1 inet static
    address 10.10.2.2
    netmask 255.255.255.252
# --- RR -> R3 ---
auto eth2
iface eth2 inet static
    address 10.10.3.2
    netmask 255.255.255.252


# --- Loopback RR ---
auto lo
iface lo inet loopback
    up ip addr add 1.1.1.1/32 dev lo