# =============================
#               R2
# =============================

# --- R2 -> RR ---
auto eth1
iface eth1 inet static
    address 10.10.2.1
    netmask 255.255.255.252


# --- R2 -> Host 2 ---
auto eth0
iface eth0 inet manual

# --- Loopback ---
auto lo
iface lo inet loopback
    up ip addr add 1.1.1.3/32 dev lo

# --- Bridge ---
auto br0
iface br0 inet manual
    bridge_ports eth0 vxlan10

# --- VXLAN VNI 10 ---
auto vxlan10
iface vxlan10 inet manual
    pre-up ip link add vxlan10 type vxlan id 10 local 1.1.1.3 dstport 4789 nolearning
    post-up ip link set vxlan10 up
    post-down ip link del vxlan10