# =============================
#               R1
# =============================

# --- R1 -> RR ---
auto eth0
iface eth0 inet static
    address 10.10.1.1
    netmask 255.255.255.252

# --- R1 -> Host 2 ---
auto eth1
iface eth1 inet manual

# --- Loopback ---
auto lo
iface lo inet loopback
    up ip addr add 1.1.1.2/32 dev lo

# --- Bridge ---
auto br0
iface br0 inet manual
    bridge_ports eth1 vxlan10

# --- VXLAN VNI 10 ---
auto vxlan10
iface vxlan10 inet manual
    pre-up ip link add vxlan10 type vxlan id 10 local 1.1.1.2 dstport 4789 nolearning
    post-up ip link set vxlan10 up
    post-down ip link del vxlan10