#
# This is a sample network config, please uncomment lines to configure the network
#

# Uncomment this line to load custom interface files
# source /etc/network/interfaces.d/*

# Static config for eth0
#mortiz-d says: this is the gateway for the host on this network
auto eth0
iface eth0 inet static
	address 10.0.1.1
	netmask 255.255.255.0

# DHCP config for eth0
#auto eth0
#iface eth0 inet dhcp
#	hostname p1-router-mortiz-d-1

# Static config for eth1
auto eth1
iface eth1 inet static
	address 10.0.2.1
	netmask 255.255.255.0

# DHCP config for eth1
#auto eth1
#iface eth1 inet dhcp
#	hostname p1-router-mortiz-d-1



